packages: []

allowBuilds:
  '@nestjs/core': false
overrides:
  '@new-hros/libs-apis': link:../../api-factory/libs/libs-apis
  '@new-hros/libs-core': link:../../api-factory/libs/libs-core
  '@new-hros/libs-sql': link:../../api-factory/libs/libs-sql
