apiVersion: v1
kind: ConfigMap
metadata:
  name: hrms-access-config
  namespace: hrms
data:
  NODE_ENV: production
  PORT: "3000"
  DB_HOST: postgres-service
  DB_PORT: "5432"
  DB_NAME: hrms_access_db
  DB_USERNAME: hrms_user
  REDIS_HOST: redis-service
  REDIS_PORT: "6379"
